[opener]
play = [
	{ run ="vlc %s", orphan = true },
]
open = [
	{ run = "qimgv %s", orphan = true },
]
edit = [
	{ run = "nvim %s", block = true },
]
pdf_open = [
	{ run = "brave %s", block = true },
]

[open]
prepend_rules = [
	{mime ="text/*", use = "edit" },
	{ url = "*.pdf", use = "pdf_open" },
]

[mgr] 
show_hidden = true
