# vim:ft=kitty

## name:     Catppuccin Kitty Diff Macchiato
## author:   Catppuccin Org
## license:  MIT

#font 
font_family family="FiraCode Nerd Font Mono"

font_size 12.0
disable_ligatures always

hide_window_decorations yes

allow_remote_control yes

# padding
window_padding_width   6

confirm_os_window_close 0
shell fish

map cmd+j second_window
map cmd+k first_window
map cmd+w close_window
map ctrl+d scroll_page_down
map ctrl+u scroll_page_up
map cmd+enter launch --cwd=current --type=window
background            #1b1d22
foreground            #e6e8ee
cursor                #f6f6ec
selection_background  #2e353d
color0                #22252b
color8                #22252b
color1                #b53f36
color9                #b53f36
color2                #5ab977
color10               #5ab977
color3                #ddb566
color11               #ddb566
color4                #6a7b92
color12               #6a7b92
color5                #a3799d
color13               #a3799d
color6                #3f93a8
color14               #3f93a8
color7                #e6e8ee
color15               #ebedf2
selection_foreground #1b1d22
